# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-03-22 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fusionCharts', '0002_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='District',
        ),
    ]
